gp_settings:
  # Covariance.
  variance_x: 1.0e-2
  variance_y: 1.0e-2
  variance_z: 1.0e-2
  # position of point P (e.g. gps receiver) in body frame.
  B_t_PB: [0.0, 0.0, 0.0]
  # Max number of global residuals for each keyframe.
  max_num_residuals: 1
  # Initialize with a known orientaion.
  # Set to true in the case the initial orientation is known (e.g. through an external motion capture system)
  initial_orientation_known: true